# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"findAlingments": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://hcstubbe.github.io/pytrim2/"

git_url = "https://github.com/hcstubbe/pytrim2/tree/master/"

def custom_doc_links(name): return None
